<?php
/**
 * Created by PhpStorm.
 * User: Peison
 * Date: 2015/4/4
 * Time: 13:40
 */

class BaseController extends Controller{
    protected function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function render($view,$data=array()){
        $data['path'] = self::loginPath();
        $data['userID'] = Yii::app()->session['userID'];
        $data["login"] = Yii::app()->session["login"];
        $data["userName"] = Yii::app()->session["userName"];
        parent::render($view,$data);
    }

    public function loginPath(){
        $path = array();
        foreach($_GET as $k => $v){
            $path[] = "$k=$v";
        };
        $path = implode('&',$path);
        return base64_encode($path);
    }
}